### ISSUE TITLE
Could not find org.cloudfoundry:spring-boot-cf-service-broker:2.5.0-async

### ISSUE THREAD

**Issue by yanglei99** [cloudfoundry-incubator/brooklyn-service-broker#11]
:clean UP-TO-DATE
:compileJava

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':compile'.
> Could not find org.cloudfoundry:spring-boot-cf-service-broker:2.5.0-async.
  Searched in the following locations:
      file:/Users/yanglei/.m2/repository/org/cloudfoundry/spring-boot-cf-service-broker/2.5.0-async/spring-boot-cf-service-broker-2.5.0-async.pom
      file:/Users/yanglei/.m2/repository/org/cloudfoundry/spring-boot-cf-service-broker/2.5.0-async/spring-boot-cf-service-broker-2.5.0-async.jar
      https://repo1.maven.org/maven2/org/cloudfoundry/spring-boot-cf-service-broker/2.5.0-async/spring-boot-cf-service-broker-2.5.0-async.pom
      https://repo1.maven.org/maven2/org/cloudfoundry/spring-boot-cf-service-broker/2.5.0-async/spring-boot-cf-service-broker-2.5.0-async.jar
      http://repo.spring.io/release/org/cloudfoundry/spring-boot-cf-service-broker/2.5.0-async/spring-boot-cf-service-broker-2.5.0-async.pom
      http://repo.spring.io/release/org/cloudfoundry/spring-boot-cf-service-broker/2.5.0-async/spring-boot-cf-service-broker-2.5.0-async.jar
      http://repo.spring.io/milestone/org/cloudfoundry/spring-boot-cf-service-broker/2.5.0-async/spring-boot-cf-service-broker-2.5.0-async.pom
      http://repo.spring.io/milestone/org/cloudfoundry/spring-boot-cf-service-broker/2.5.0-async/spring-boot-cf-service-broker-2.5.0-async.jar
      http://repo.spring.io/snapshot/org/cloudfoundry/spring-boot-cf-service-broker/2.5.0-async/spring-boot-cf-service-broker-2.5.0-async.pom
      http://repo.spring.io/snapshot/org/cloudfoundry/spring-boot-cf-service-broker/2.5.0-async/spring-boot-cf-service-broker-2.5.0-async.jar
      https://repository.apache.org/content/repositories/snapshots/org/cloudfoundry/spring-boot-cf-service-broker/2.5.0-async/spring-boot-cf-service-broker-2.5.0-async.pom
      https://repository.apache.org/content/repositories/snapshots/org/cloudfoundry/spring-boot-cf-service-broker/2.5.0-async/spring-boot-cf-service-broker-2.5.0-async.jar
  Required by:
      :brooklyn-service-broker:unspecified

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 11.293 secs

**Comment by robertgmoss** [comment]
Hi @yanglei99 

We are currently building from the [async branch](https://github.com/robertgmoss/spring-boot-cf-service-broker/tree/async) from my fork of spring-boot-cf-service-broker.  This is because we are waiting for some functionality to be merged into that project.

Unfortunately this is not on in maven central so If you want to build this project you will need to run:

    ./gradlew publishToMavenLocal

on my fork, before trying to build the Brooklyn-Service-Broker.

**Comment by yanglei99** [comment]
I did the following still hit build exception.

git clone https://github.com/robertgmoss/spring-boot-cf-service-broker.git
cd spring-boot-cf-service-broker
./gradlew publishToMavenLocal

then got to my brooklyn-service-broker directory and : gradle clean build.

The exception:

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':compile'.
> Could not find org.cloudfoundry:spring-boot-cf-service-broker:2.5.0-async.
  Searched in the following locations:
      file:/Users/yanglei/.m2/repository/org/cloudfoundry/spring-boot-cf-service-broker/2.5.0-async/spring-boot-cf-service-broker-2.5.0-async.pom
      file:/Users/yanglei/.m2/repository/org/cloudfoundry/spring-boot-cf-service-broker/2.5.0-async/spring-boot-cf-service-broker-2.5.0-async.jar
      https://repo1.maven.org/maven2/org/cloudfoundry/spring-boot-cf-service-broker/2.5.0-async/spring-boot-cf-service-broker-2.5.0-async.pom
      https://repo1.maven.org/maven2/org/cloudfoundry/spring-boot-cf-service-broker/2.5.0-async/spring-boot-cf-service-broker-2.5.0-async.jar
      http://repo.spring.io/release/org/cloudfoundry/spring-boot-cf-service-broker/2.5.0-async/spring-boot-cf-service-broker-2.5.0-async.pom
      http://repo.spring.io/release/org/cloudfoundry/spring-boot-cf-service-broker/2.5.0-async/spring-boot-cf-service-broker-2.5.0-async.jar
      http://repo.spring.io/milestone/org/cloudfoundry/spring-boot-cf-service-broker/2.5.0-async/spring-boot-cf-service-broker-2.5.0-async.pom
      http://repo.spring.io/milestone/org/cloudfoundry/spring-boot-cf-service-broker/2.5.0-async/spring-boot-cf-service-broker-2.5.0-async.jar
      http://repo.spring.io/snapshot/org/cloudfoundry/spring-boot-cf-service-broker/2.5.0-async/spring-boot-cf-service-broker-2.5.0-async.pom
      http://repo.spring.io/snapshot/org/cloudfoundry/spring-boot-cf-service-broker/2.5.0-async/spring-boot-cf-service-broker-2.5.0-async.jar
      https://repository.apache.org/content/repositories/snapshots/org/cloudfoundry/spring-boot-cf-service-broker/2.5.0-async/spring-boot-cf-service-broker-2.5.0-async.pom
      https://repository.apache.org/content/repositories/snapshots/org/cloudfoundry/spring-boot-cf-service-broker/2.5.0-async/spring-boot-cf-service-broker-2.5.0-async.jar
  Required by:
      :brooklyn-service-broker:unspecified

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 9.473 secs
Yangs-Work-MacBook-Pro:brooklyn-service-broker yanglei$ ls /Users/yanglei/.m2/repository/org/cloudfoundry/spring-boot-cf-service-broker
2.4.2				maven-metadata-local.xml

**Comment by robertgmoss** [comment]
try 
    git checkout async

**Comment by yanglei99** [comment]
Problem solved. Thanks.

**Comment by Wa3ess1** [comment]
Hi,

got this error too

 I have done all steps above but without any success.

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':compile'.
> Could not resolve org.cloudfoundry:spring-boot-cf-service-broker:2.5.0-async.
  Required by:
      :brooklyn-service-broker:unspecified
   > Could not resolve org.cloudfoundry:spring-boot-cf-service-broker:2.5.0-async.
      > Could not get resource 'http://repo.spring.io/release/org/cloudfoundry/spring-boot-cf-service-broker/2.5.0-async/spring-boot-cf-service-broker-2.5.0-async.pom'.
..........

I try to this comand unsuccessfully - git checkout async

Find -- that the url 
http://repo.spring.io/snapshot/org/cloudfoundry/spring-boot-cf-service-broker/2.5.0-async/spring-boot-cf-service-broker-2.5.0-async.pom  

is pointing to "nothing" - Output

{
  "errors" : [ {
    "status" : 404,
    "message" : "Could not find resource"
  } ]
}

-------------------
Any suggestion howto fix this error / runing this build.
Thanks

**Comment by robertgmoss** [comment]
@Wa3ess1 I have updated docs/build-and-test.md to reflect the steps required.

**Comment by Wa3ess1** [comment]
@robertgmoss Thanks - build process is now working with the description.
