### ISSUE TITLE
How to create an application manifest and use it

### ISSUE THREAD

**Issue by jiangchuan1220** [cloudfoundry-incubator/brooklyn-service-broker#14]
When deploying brooklyn service broker, the launch.md says I should create an application manifest before cf push the war package. How to create the application manifest and use it?

Thanks,
Jiang chuan.

**Comment by robertgmoss** [comment]
@jiangchuan1220 
There is an example manifest on that page but for more general info see [this](http://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html)
