### ISSUE TITLE
Problem accessing /v2/catalog. Reason: Not found

### ISSUE THREAD

**Issue by StBurcher** [cloudfoundry-incubator/brooklyn-service-broker#26]
Hi,

I trying to deploy brooklyn service broker on CF250 with an AMP Brooklyn Backend. But, I get an error during create-service-broker. 
AMP Brooklyn is working find. CF also. See the following error message.

```
cf create-service-broker brooklyn amp4 Amp4! http://139.25.25.251:4443        Creating service broker brooklyn as admin...
FAILED
Server error, status code: 502, error code: 10001, message: The service broker rejected the request to http://139.25.25.251:4443/v2/catalog. Status Code: 404 Not Found, Body: <html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<title>Error 404 Not Found</title>
</head>
<body><h2>HTTP ERROR 404</h2>
<p>Problem accessing /v2/catalog. Reason:
<pre>    Not Found</pre></p><hr><i><small>Powered by Jetty://</small></i><hr/>

</body>
</html>
```

**Comment by robertgmoss** [comment]
Hi @StBurcher 

I suspect your command `cf create-service-broker brooklyn amp4 Amp4! http://139.25.25.251:4443` is trying to use AMP as a Broker, which it is not.  

You have to run the Brooklyn-Service-Broker as an app with its environment populated with the AMP connection details.  That will give you a new url, which is the one you need to pass into your `cf create-service` command.

**Comment by StBurcher** [comment]
Good Morning @robertgmoss 
thank you for the response. 
The app is running in the space

```
C:\Users\Z003PCEU>cf apps
Getting apps in org cloudlab / space demo as admin...
OK

name                      requested state   instances   memory   disk   urls
cf-intro                  started           1/1         64M      1G     cf-intro.de.cloudlab.com
cf-webui                  started           1/1         128M     1G     console-cf-webui.de.cloudlab.com
Brooklyn-Service-Broker   started           1/1         1G       1G     brooklyn-service-broker.de.cloudlab.com
```

I thought the command cf create-service-broker connects the broker app with the brooklyn backend.  Only different is that we are using a Softcloud AMP instead of an Apache brooklyn.

**Comment by robertgmoss** [comment]
your `cf create-service-broker` command should use `http://brooklyn-service-broker.de.cloudlab.com` rather than `http://139.25.25.251:4443` and the username and password should be whatever you put in the Env for your `Brooklyn-Service-Broker` app.  i.e if you run `cf env Brooklyn-Service-Broker` whatever the values of `SECURITY_USER_NAME`, `SECURITY_USER_PASSWORD` are.

**Comment by StBurcher** [comment]
Thank you it works.
